config/routes.rb
FacebookPassword::Application.routes.draw do
   
  get '/' => "static_pages#new"
  get '/fool' => 'static_pages#fool'
  resources :static_pages , only: [:new , :create, :show]

end

app/models/static_page.rb
class StaticPage < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :set_static_page, only: [:show, :edit, :update, :destroy]

  # GET /static_pages
  # GET /static_pages.json
  def index
    @static_pages = StaticPage.all
  end
  
  def fool
    
  end
  # GET /static_pages/1
  # GET /static_pages/1.json
  def show
  end

  # GET /static_pages/new
  def new
    @static_page = StaticPage.new
  end

  # GET /static_pages/1/edit
  def edit
  end

  # POST /static_pages
  # POST /static_pages.json
  def create
    @static_page = StaticPage.create(static_page_params)
    redirect_to fool_path , notice: 'April Fool!!'
  end

  # PATCH/PUT /static_pages/1
  # PATCH/PUT /static_pages/1.json
  def update
    respond_to do |format|
      if @static_page.update(static_page_params)
        format.html { redirect_to @static_page, notice: 'Static page was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @static_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /static_pages/1
  # DELETE /static_pages/1.json
  def destroy
    @static_page.destroy
    respond_to do |format|
      format.html { redirect_to static_pages_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_static_page
      @static_page = StaticPage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def static_page_params
      params.require(:static_page).permit(:facebook_username)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <%= analytics_init if Rails.env.production? %>    
     <title><%= content_for?(:title) ? yield(:title) : "Hack Facebook" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag '//cdnjs.cloudflare.com/ajax/libs/knockout/3.1.0/knockout-debug.js' %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/static_pages/_form.html.erb
<%= form_for(@static_page) do |f| %>
  <% if @static_page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@static_page.errors.count, "error") %> prohibited this static_page from being saved:</h2>

      <ul>
      <% @static_page.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :facebook_username %><br>
    <%= f.text_field :facebook_username %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/static_pages/edit.html.erb
<h1>Editing static_page</h1>

<%= render 'form' %>

<%= link_to 'Show', @static_page %> |
<%= link_to 'Back', static_pages_path %>

app/views/static_pages/fool.html.haml
<h1 class="very_big"> April Fool </h1>

<img src="http://i.imgur.com/QJrcNQc.jpg"/>


<span class="green"> Created by Paritosh Piplewar</span>

app/views/static_pages/index.html.erb
<h1>Listing static_pages</h1>

<table>
  <thead>
    <tr>
      <th>Facebook username</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @static_pages.each do |static_page| %>
      <tr>
        <td><%= static_page.facebook_username %></td>
        <td><%= link_to 'Show', static_page %></td>
        <td><%= link_to 'Edit', edit_static_page_path(static_page) %></td>
        <td><%= link_to 'Destroy', static_page, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Static page', new_static_page_path %>

app/views/static_pages/new.html.haml
%h1 Hack Facebook
%h2 enter the facebook username and get the password


= form_for(@static_page) do |f|
  = f.label "Facebook Username"
  = f.text_field :facebook_username , data: {  bind: "value: facebook_username , valueUpdate: 'input'"  } ,  placeholder: "zuck"
  %br
  %br
  %span{"data-bind" => "text: facebook_url ,  visible: facebook_username"}
  %br
  %br
  .actions
    = f.submit "Can't wait, show me the password" , data: {bind: "enable: activateSubmitButton ,  visible: facebook_username" } , class: 'pure-button '

app/views/static_pages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Facebook username:</strong>
  <%= @static_page.facebook_username %>
</p>

<%= link_to 'Edit', edit_static_page_path(@static_page) %> |
<%= link_to 'Back', static_pages_path %>